name: dna_toolbox Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Build the dna_toolbox's Docker image 
      run: docker build . --file bioinformatics/dna_toolbox.dockerfile --tag ${{secrets.DOCKER_USER}}/dna_toolbox:latest
      # $(date +%s)
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/dna_toolbox
